const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT_DIR = path.resolve(__dirname, '..');
const LOCAL_PROPERTIES_PATH = path.join(ROOT_DIR, 'local.properties');
const WEB_ENV_PATH = path.join(ROOT_DIR, 'src', '.env.local');

function syncConfig() {
  console.log('--- NEURALATLAS SYNC: Absolute Master Config (Local -> App & Vercel) ---');

  // 1. Graceful check for local.properties (CI-Aware)
  if (!fs.existsSync(LOCAL_PROPERTIES_PATH)) {
    if (process.env.VERCEL || process.env.CI) {
      console.warn('--- SYNC SKIPPED: local.properties not found in cloud environment. ---');
      console.warn('Ensure all environment variables (e.g., ADMOB_APP_ID) are set in your platform dashboard.');
      process.exit(0); // Success exit to allow CI build to continue
    } else {
      console.error('Error: local.properties (The Absolute Master) not found in root.');
      console.error('This file is required for local development and build synchronization.');
      process.exit(1);
    }
  }

  const fileConfig = {};
  const propertiesContent = fs.readFileSync(LOCAL_PROPERTIES_PATH, 'utf-8');
  propertiesContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, ...valueParts] = trimmed.split('=');
    if (key && valueParts.length > 0) {
      fileConfig[key.trim()] = valueParts.join('=').trim();
    }
  });
  console.log('Loaded Master Config from local.properties.');

  // Master Keys -> [One or more Web Env keys]
  const mapping = {
    'ADMOB_APP_ID': ['NEXT_PUBLIC_ADMOB_APP_ID'],
    'ADMOB_BANNER_AD_UNIT': ['NEXT_PUBLIC_ADMOB_BANNER_ID'],
    'ADMOB_INTERSTITIAL_AD_UNIT': ['NEXT_PUBLIC_ADMOB_INTERSTITIAL_ID'],
    'GOOGLE_WEB_CLIENT_ID': ['NEXT_PUBLIC_GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_ID'],
    'REVENUECAT_PUBLIC_KEY': ['NEXT_PUBLIC_REVENUECAT_KEY'],
    'VERCEL_KV_REST_URL': ['KV_REST_API_URL'],
    'VERCEL_KV_REST_TOKEN': ['KV_REST_API_TOKEN'],
    'REDIS_URL': ['REDIS_URL'],
    'GOOGLE_CLIENT_SECRET': ['GOOGLE_CLIENT_SECRET'],
    'NEXTAUTH_SECRET': ['NEXTAUTH_SECRET'],
    'NEXTAUTH_URL': ['NEXTAUTH_URL'],
    'LAN_ROOM_SERVER_URL': ['NEXT_PUBLIC_LAN_SERVER_URL'],
  };

  let envContent = '# AUTO-GENERATED BY NEURALATLAS SYNC - ONLY EDIT local.properties\n';
  let syncedKeys = [];

  Object.entries(mapping).forEach(([masterKey, webKeys]) => {
    const value = fileConfig[masterKey];
    if (value && value.trim() !== '') {
      webKeys.forEach(webKey => {
        envContent += `${webKey}=${value}\n`;
        syncedKeys.push({ master: masterKey, web: webKey, value });
      });
    }
  });

  // 2. Sync to Local Web App (.env.local)
  fs.writeFileSync(WEB_ENV_PATH, envContent, 'utf-8');
  console.log(`Synced: Updated src/.env.local with ${syncedKeys.length} mapped values.`);

  // 3. Sync to Vercel (Only if running locally and CLI is detected)
  if (!process.env.VERCEL && !process.env.CI) {
    console.log('\n--- ATTEMPTING CLOUD SYNC: local.properties -> Vercel ---');
    try {
      execSync('npx vercel --version', { stdio: 'ignore' });
      
      syncedKeys.forEach(({ web, value }) => {
        try {
          console.log(`Cloud Push: ${web}...`);
          execSync(`npx vercel env add ${web} "${value}" production -f`, { stdio: 'ignore' });
        } catch (err) {
          // Failure here is usually because project isn't linked, we log and continue
          console.warn(`Could not push ${web} to Vercel. Ensure 'npx vercel link' is done.`);
        }
      });
      console.log('--- CLOUD SYNC ATTEMPT COMPLETE ---');
    } catch (e) {
      console.warn('Vercel CLI not detected. Skipping Cloud Push.');
    }
  }

  console.log('\n--- MASTER SYNC COMPLETE ---\n');
}

syncConfig();
