const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT_DIR = path.resolve(__dirname, '..');
const LOCAL_PROPERTIES_PATH = path.join(ROOT_DIR, 'local.properties');
const WEB_ENV_PATH = path.join(ROOT_DIR, 'src', '.env.local');

function syncConfig() {
  console.log('--- NEURALATLAS SYNC: Absolute Master Config (Local -> App & Vercel) ---');

  if (!fs.existsSync(LOCAL_PROPERTIES_PATH)) {
    console.error('Error: local.properties (The Absolute Master) not found.');
    process.exit(1);
  }

  const fileConfig = {};
  const propertiesContent = fs.readFileSync(LOCAL_PROPERTIES_PATH, 'utf-8');
  propertiesContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, ...valueParts] = trimmed.split('=');
    if (key && valueParts.length > 0) {
      fileConfig[key.trim()] = valueParts.join('=').trim();
    }
  });
  console.log('Loaded Master Config from local.properties.');

  // Master Keys -> [One or more Web Env keys]
  const mapping = {
    'GOOGLE_WEB_CLIENT_ID': ['NEXT_PUBLIC_GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_ID'],
    'ADMOB_APP_ID': ['NEXT_PUBLIC_ADMOB_APP_ID'],
    'ADMOB_BANNER_AD_UNIT': ['NEXT_PUBLIC_ADMOB_BANNER_ID'],
    'ADMOB_INTERSTITIAL_AD_UNIT': ['NEXT_PUBLIC_ADMOB_INTERSTITIAL_ID'],
    'REVENUECAT_PUBLIC_KEY': ['NEXT_PUBLIC_REVENUECAT_KEY'],
    'VERCEL_KV_REST_URL': ['KV_REST_API_URL'],
    'VERCEL_KV_REST_TOKEN': ['KV_REST_API_TOKEN'],
    'REDIS_URL': ['REDIS_URL'],
    'GOOGLE_CLIENT_SECRET': ['GOOGLE_CLIENT_SECRET'],
    'NEXTAUTH_SECRET': ['NEXTAUTH_SECRET'],
    'NEXTAUTH_URL': ['NEXTAUTH_URL'],
  };

  let envContent = '# AUTO-GENERATED BY NEURALATLAS SYNC - ONLY EDIT local.properties\n';
  let syncedKeys = [];

  Object.entries(mapping).forEach(([masterKey, webKeys]) => {
    const value = fileConfig[masterKey];
    if (value && value.trim() !== '') {
      webKeys.forEach(webKey => {
        envContent += `${webKey}=${value}\n`;
        syncedKeys.push({ master: masterKey, web: webKey, value });
      });
    } else {
      console.warn(`Warning: Master key '${masterKey}' has no value. Skipping.`);
    }
  });

  // 1. Sync to Local Web App (.env.local)
  fs.writeFileSync(WEB_ENV_PATH, envContent, 'utf-8');
  console.log(`Synced: Updated src/.env.local with ${syncedKeys.length} values.`);

  // 2. Sync to Vercel (Only if running locally and logged in)
  if (!process.env.VERCEL && !process.env.CI) {
    console.log('\n--- ATTEMPTING CLOUD SYNC: local.properties -> Vercel ---');
    try {
      // Check if vercel is installed
      execSync('npx vercel --version', { stdio: 'ignore' });
      
      syncedKeys.forEach(({ web, value }) => {
        try {
          // Add/Update the variable on Vercel (Production environment)
          // We use -f to force overwrite if it exists
          console.log(`Cloud Syncing: ${web}...`);
          execSync(`npx vercel env add ${web} "${value}" production -f`, { stdio: 'ignore' });
        } catch (err) {
          console.warn(`Could not sync ${web} to Vercel cloud. Ensure your project is linked via 'npx vercel link'.`);
        }
      });
      console.log('--- CLOUD SYNC COMPLETE ---');
    } catch (e) {
      console.warn('Vercel CLI not detected or not logged in. Skipping Cloud Sync.');
    }
  } else {
    console.log('Detected CI/Vercel environment. Skipping Cloud Sync to avoid recursion.');
  }

  console.log('\n--- MASTER SYNC COMPLETE ---\n');
}

syncConfig();
