const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const LOCAL_PROPERTIES_PATH = path.join(ROOT_DIR, 'local.properties');
const WEB_ENV_PATH = path.join(ROOT_DIR, 'src', '.env.local');

function syncConfig() {
  console.log('--- NEURALATLAS SYNC: Master Config -> Web Environment ---');

  if (!fs.existsSync(LOCAL_PROPERTIES_PATH)) {
    console.error('Error: local.properties not found in root.');
    process.exit(1);
  }

  const propertiesContent = fs.readFileSync(LOCAL_PROPERTIES_PATH, 'utf-8');
  const lines = propertiesContent.split('\n');
  const config = {};

  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, ...valueParts] = trimmed.split('=');
    if (key && valueParts.length > 0) {
      config[key.trim()] = valueParts.join('=').trim();
    }
  });

  // Map local.properties keys to .env.local keys
  const mapping = {
    'GOOGLE_WEB_CLIENT_ID': 'NEXT_PUBLIC_GOOGLE_CLIENT_ID',
    'ADMOB_APP_ID': 'NEXT_PUBLIC_ADMOB_APP_ID',
    'ADMOB_BANNER_AD_UNIT': 'NEXT_PUBLIC_ADMOB_BANNER_ID',
    'ADMOB_INTERSTITIAL_AD_UNIT': 'NEXT_PUBLIC_ADMOB_INTERSTITIAL_ID',
    'REVENUECAT_PUBLIC_KEY': 'NEXT_PUBLIC_REVENUECAT_KEY',
    'VERCEL_KV_REST_URL': 'KV_REST_API_URL',
    'VERCEL_KV_REST_TOKEN': 'KV_REST_API_TOKEN',
  };

  let envContent = '# AUTO-GENERATED BY NEURALATLAS SYNC - DO NOT EDIT MANUALLY\n';
  
  Object.entries(mapping).forEach(([propKey, envKey]) => {
    if (config[propKey]) {
      envContent += `${envKey}=${config[propKey]}\n`;
      console.log(`Synced: ${propKey} -> ${envKey}`);
    } else {
      console.warn(`Warning: ${propKey} missing in local.properties`);
    }
  });

  fs.writeFileSync(WEB_ENV_PATH, envContent, 'utf-8');
  console.log('--- SYNC COMPLETE: src/.env.local updated ---\n');
}

syncConfig();
